practise/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('practises.urls', namespace='practises')),
]

practises/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	#Home Page
	url(r'^$', views.index, name='index'),
	#Show all topics
	url(r'^topics/$', views.topics, name='topics'),
	#Edit a topic -----
	url(r'^edit_topic/(?P<topic_id>\d+)/$', views.edit_topic, name='edit_topic'),
	#Detail for single topic
	url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
	#Page to add new topic
	url(r'^new_topic/$', views.new_topic, name='new_topic'),
	#Adding a new entry
	url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
	#Page for editing entries
	url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Define URL patterns for users"""

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
	#Login page
	url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
	#Log out page
	url(r'^logout/$', views.logout_view, name='logout'),
	#Registration page
	url(r'^register/$', views.register, name='register'),
]

practises/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
	"""A topic the user is learning about"""
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User)

	def __str__(self):
		"""Return a string representation of the model"""
		return self.text

class Entry(models.Model):
	"""Write about the topic"""
	topic = models.ForeignKey(Topic)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'entries'

	def __str__(self):
		"""Return a string representation of the model"""
		return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

practises/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text': ''}

class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}

practises/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def index(request):
	"""The homepage for learning log"""
	return render(request, 'practises/index.html')

@login_required
def topics(request):
	"""Shows all topics"""
	topics = Topic.objects.filter(owner=request.user).order_by('date_added')
	context = {'topics': topics}
	return render(request, 'practises/topics.html', context)

@login_required
def topic(request, topic_id):
	"""Shows all topics"""
	topic = Topic.objects.get(id=topic_id)
	#Make sure the topic belongs to the current user
	if topic.owner != request.user:
		raise Http404
	entries = topic.entry_set.order_by('-date_added')
	context = {'topic': topic, 'entries': entries}
	return render(request, 'practises/topic.html', context)

@login_required
def new_topic(request):
	"""Add a new topic"""
	if request.method != 'POST':
		#No data submitted, submit a blank form
		form = TopicForm()
	else:
		#POST data submitted, process data
		form = TopicForm(request.POST)
		if form.is_valid():
			new_topic = form.save(commit=False)
			new_topic.owner = request.user
			new_topic.save()
			return HttpResponseRedirect(reverse('practises:topics'))

	context = {'form': form}
	return render(request, 'practises/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
	#Add new entry for a particular topic
	topic = Topic.objects.get(id=topic_id)

	if request.method != 'POST':
		#No data submitted, submit a blank form
		form = EntryForm()
	else:
		#POST data submitted, process data
		form = EntryForm(data=request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			new_entry.save()
			return HttpResponseRedirect(reverse('practises:topic', args=[topic_id]))

	context = {'topic': topic, 'form': form}
	return render(request, 'practises/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
	"""Edit an existing entry"""
	entry = Entry.objects.get(id=entry_id)
	topic = entry.topic   #Didnt write this line for my edit topic view
	if topic.owner != request.user:
		raise Http404

	if request.method != 'POST':
		#Initial request; pre-fill form with the current entry
		form = EntryForm(instance=entry)
	else:
		#POST data submitted, submit data
		form = EntryForm(instance=entry, data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('practises:topic', args=[topic.id]))

	context = {'entry': entry, 'topic': topic, 'form': form}
	return render(request, 'practises/edit_entry.html', context)

@login_required
def edit_topic(request, topic_id):
	"""Edit an existing topic"""
	topic = Topic.objects.get(id=topic_id)
	if topic.owner != request.user:
		raise Http404

	if request.method != 'POST':
		#No data submitted, submit a blank form
		form = TopicForm(instance=topic)
	else:
		#POST dat submitted, submit data
		form = TopicForm(instance=topic, data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('practises:topic', args=[topic.id]))

	context = {'topic': topic, 'form': form}
	return render(request, 'practises/edit_topic.html', context)

	
	

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
	"""Log the user out"""
	logout(request)
	return HttpResponseRedirect(reverse('practises:index'))

def register(request):
	"""Register a new user"""
	if request.method != 'POST':
		#Display blank registration form
		form = UserCreationForm()
	else:
		#Process completed form
		form = UserCreationForm(data=request.POST)

		if form.is_valid():
			new_user = form.save()
			#Log the user in and redirect to home page
			authenticated_user = authenticate(username=new_user.username,
				password=request.POST['password1'])
			login(request, authenticated_user)
			return HttpResponseRedirect(reverse('practises:index'))

	context = {'form': form}
	return render(request, 'users/register.html', context)

practises/templates/practises/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>Practises</title>

{% bootstrap_css %}
{% bootstrap_javascript %}

</head>

<body>
	
	<!-- Static Navbar -->

	<nav class="navbar navbar-default navbar-static-top">
		<div class="container">

		<div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed"
			data-toggle="collapse" data-target="#navbar"
			aria-expanded="false" aria-controls="navbar">
		</button>
		<a class="navbar-brand" href="{% url 'practises:index' %}">Practice</a>
		</div>

		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li><a href="{% url 'practises:topics' %}">Topics</a></li>
			</ul>

			<ul class="nav navbar-nav navbar-right"> 
				{% if user.is_authenticated %}
					<li><a>Hello, {{ user.username }}.</a></li>
					<li><a href="{% url 'users:logout' %}">Log out</a></li>
				{% else %}
					<li><a href="{% url 'users:register' %}">Register</a></li>
					<li><a href="{% url 'users:login' %}">Log in</a></li>
				{% endif %}
			</ul>			
		</div><!--/.nav-collapse -->
			
		</div>
		
	</nav>

	<div class="container">
		
		<div class="page-header">
			{% block header %}{% endblock header %}
		</div>
		<div>
			{% block content %}{% endblock content %}
		</div>

	</div><!--/container -->
</body>

practises/templates/practises/edit_entry.html
{% extends 'practises/base.html' %}

{% block content %}
	
	<p><a href="{% url 'practises:topic' topic.id %}">{{ topic }}</a></p>

	<p>Edit entry: </p>
	<form action="{% url 'practises:edit_entry' entry.id %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Save changes</button>
	</form>		

{% endblock content %}

practises/templates/practises/edit_topic.html
{% extends 'practises/base.html' %}

{% block content %}

	<p><a href="{% url 'practises:topic' topic.id %}">{{ topic }}</a></p>

	<p>Edit topic: </p>

	<form action="{% url 'practises:edit_topic' topic.id %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Save changes</button>
	</form>		

{% endblock content %}

practises/templates/practises/index.html
{% extends "practises/base.html" %}

{% block header %}
	<div class="jumbotron">
		<h1>Django Practise</h1>
	</div>
{% endblock header %}

{% block content %}
	<h2>
		<a href="{% url 'users:register' %}">Register an account</a> to start
		practising, and also list the topics you want to practise with.
	</h2>
	<h2>
		Whenever you practise, make a topic, followed by an entry in the topic
		about what you just practised.
	</h2>
{% endblock content %}

practises/templates/practises/new_entry.html
{% extends 'practises/base.html' %}

{% block content %}
	
	<p><a href="{% url 'practises:topic' topic.id %}">{{ topic }}</a></p>

	<p>Add a new entry: </p>
	<form action="{% url 'practises:new_entry' topic.id %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Add Entry</button>
	</form>		

{% endblock content %}

practises/templates/practises/new_topic.html
{% extends 'practises/base.html' %}
{% load bootstrap3 %}


{% block header %}
	<h2>Add a new topic</h2>
{% endblock header %}

{% block content %}

	<form action="{% url 'practises:new_topic' %}" method='post' class="form">
		{% csrf_token %}
		{% bootstrap_form form %}

		{% buttons %}
			<button name="submit" class="btn btn-primary">Add Topic</button>
		{% endbuttons %}
		
	</form>		

{% endblock content %}

practises/templates/practises/topic.html
{% extends 'practises/base.html' %}

{% block header %}
	<h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}

	<!-- <p>
		<a href="{% url 'practises:edit_topic' topic.id %}">Edit topic</a>
	</p> -->
	<p>
		<a href="{% url 'practises:new_entry' topic.id %}">Add new entry</a>
	</p>
	{% for entry in entries %}
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3>
					{{ entry.date_added|date:'M d, Y H:i' }}
					<small>
						<a href="{% url 'practises:edit_entry' entry.id %}">Edit entry</a>
					</small>
				</h3>
				<div class="panel-body">
					{{ entry.text|linebreaks }}
				</div>
			</div>
		</div><!-- panel -->
		
	{% empty %}
		  There are no entries for this post yet
	{% endfor %}

{% endblock content %}

practises/templates/practises/topics.html
{% extends "practises/base.html" %}

{% block header %}
	<h1>Topics</h1>
{% endblock header %}

{% block content %}

	<ul>
		{% for topic in topics %}
			<li>
				<h3>
				<a href="{% url 'practises:topic' topic.id %}">{{ topic }}</a>
				</h3>
			</li>
		{% empty %}
			<li>No topics yet.</li>
		{% endfor %}
	</ul>

	<h3><a href="{% url 'practises:new_topic' %}">Add new topic</a></h3>

{% endblock content %}

users/templates/users/login.html
{% extends 'practises/base.html' %}
{% load bootstrap3 %}

{% block header %}
	<h2>
		Log into your account
	</h2>
{% endblock header %}

{% block content %}

	{% if form.errors %}
	<p>Yours Username and Password didnt match. Please try again</p>
	{% endif %}

	<form method="post" action="{% url 'users:login' %}" class="form">
	{% csrf_token %}
	{% bootstrap_form form %}

	{% buttons %}
		<button name="submit" class="btn btn-primary">Log in</button>
	{% endbuttons %}

	<input type="hidden" name="next" value="{% url 'practises:index' %}">
	</form>

{% endblock content %}

users/templates/users/register.html
{% extends 'practises/base.html' %}

{% block content %}

	<form method="post" action="{% url 'users:register' %}">
	{% csrf_token %}
	{{ form.as_p }}

	<button name="submit">Register</button>
	<input type="hidden" name="next" value="{% url 'practises:index' %}">
	</form>

{% endblock content %}